function exceptiontest(){
	var a=50;
	var b=0;
	try{
		if(b==0){
			throw('divided by 0 is not possible');
			{else{alert(a/b);
			}
		}catch(e){
			alert(e);
		}
		
}